In [1]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv('D:/IMS Proschool/Business Analytics/Practice/Self/Glass_Quality_Participants_Data/Train.csv')
data.head()

grade_A_Component_1  grade_A_Component_2  max_luminosity  thickness  xmin  \
0                    0                    1             150         36   144   
1                    1                    0             134         55  1144   
2                    1                    0             135         65   950   
3                    0                    1             123         35    41   
4                    1                    0             138         69   462   

   xmax     ymin     ymax  pixel_area     log_area  x_component_1  \
0   172   947225   947332         439   439.099273              0   
1  1152  2379058  2379624         329   329.205616              1   
2   974  1038442  1036754         300   300.120598              0   
3   220  1705580  1705604        6803  6803.778622              0   
4   466  1088124  1086579         251   251.401943              0   

   x_component_2  x_component_3  x_component_4  x_component_5  class  
0              0              1              0              0      1  
1              0              0              0              0      1  
2              0              0              0              0      2  
3              0              1              0              0      1  
4              0              0              0              0      2

In [3]:
data.shape

(1358, 16)

In [4]:
data.isna().sum()

grade_A_Component_1    0
grade_A_Component_2    0
max_luminosity         0
thickness              0
xmin                   0
xmax                   0
ymin                   0
ymax                   0
pixel_area             0
log_area               0
x_component_1          0
x_component_2          0
x_component_3          0
x_component_4          0
x_component_5          0
class                  0
dtype: int64

In [7]:
data['class'] = data['class'].replace(2,0)
data.head()

grade_A_Component_1  grade_A_Component_2  max_luminosity  thickness  xmin  \
0                    0                    1             150         36   144   
1                    1                    0             134         55  1144   
2                    1                    0             135         65   950   
3                    0                    1             123         35    41   
4                    1                    0             138         69   462   

   xmax     ymin     ymax  pixel_area     log_area  x_component_1  \
0   172   947225   947332         439   439.099273              0   
1  1152  2379058  2379624         329   329.205616              1   
2   974  1038442  1036754         300   300.120598              0   
3   220  1705580  1705604        6803  6803.778622              0   
4   466  1088124  1086579         251   251.401943              0   

   x_component_2  x_component_3  x_component_4  x_component_5  class  
0              0              1              0              0      1  
1              0              0              0              0      1  
2              0              0              0              0      0  
3              0              1              0              0      1  
4              0              0              0              0      0

In [8]:
data.grade_A_Component_1.unique()

array([0, 1], dtype=int64)

In [9]:
data.grade_A_Component_2.unique()

array([1, 0], dtype=int64)

In [10]:
data = data.drop(['grade_A_Component_2'], axis=1)

In [11]:
features = data.drop(['class'], axis=1)
label = data['class']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(features, label, test_size=0.2)

In [13]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
X_train = std.fit_transform(X_train)
X_val = std.transform(X_val)

In [15]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.svm import SVC

In [20]:
lr = LogisticRegression()
dt = DecisionTreeClassifier()
rf = RandomForestClassifier(n_estimators=100, max_features=5)
knn = KNeighborsClassifier(n_neighbors=3)
nb = GaussianNB()
xgb = XGBClassifier()
svm = SVC(kernel='linear', probability=True, C=7)

In [21]:
lr_score = cross_val_score(lr, X_train, y_train, cv=5, scoring='neg_log_loss')
dt_score = cross_val_score(dt, X_train, y_train, cv=5, scoring='neg_log_loss')
rf_score = cross_val_score(rf, X_train, y_train, cv=5, scoring='neg_log_loss')
knn_score = cross_val_score(knn, X_train, y_train, cv=5, scoring='neg_log_loss')
nb_score = cross_val_score(nb, X_train, y_train, cv=5, scoring='neg_log_loss')
xgb_score = cross_val_score(xgb, X_train, y_train, cv=5, scoring='neg_log_loss')
svm_score = cross_val_score(svm, X_train, y_train, cv=5, scoring='neg_log_loss')

In [22]:
print('lr',lr_score.mean())
print('dt',dt_score.mean())
print('rf',rf_score.mean())
print('knn',knn_score.mean())
print('nb',nb_score.mean())
print('xgb',lr_score.mean())
print('svm',lr_score.mean())

lr -0.32617536292126004
dt -5.6295348786033985
rf -0.3132587596692314
knn -1.9552535932664543
nb -7.441762186776785
xgb -0.32617536292126004
svm -0.32617536292126004


In [19]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier

gbc = GradientBoostingClassifier(n_estimators=100, max_features=8)
etc = ExtraTreesClassifier(n_estimators=80, max_features=7)

gbc_score = cross_val_score(gbc, X_train, y_train, cv=5, scoring='neg_log_loss')
etc_score = cross_val_score(etc, X_train, y_train, cv=5, scoring='neg_log_loss')

print('gbc',gbc_score.mean())
print('etc',etc_score.mean())

gbc -0.3157968208235217
etc -0.28361848668655587


In [24]:
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import StratifiedKFold

bc = BaggingClassifier(base_estimator=ExtraTreesClassifier(n_estimators=80, max_features=7), random_state=0)

scores = cross_val_score(bc, X_train, y_train, scoring = 'neg_log_loss', cv = StratifiedKFold(n_splits = 5, shuffle = True))

print(scores.mean())

-0.2880411496062184


In [25]:
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import StratifiedKFold

bc = BaggingClassifier(base_estimator=ExtraTreesClassifier(n_estimators=80, max_features=7), random_state=0)

scores = cross_val_score(bc, features, label, scoring = 'neg_log_loss', cv = StratifiedKFold(n_splits = 5, shuffle = True))

print(scores.mean())

-0.27606453283876037


In [26]:
etc_score = cross_val_score(etc, features, label, cv=5, scoring='neg_log_loss')

print('etc',etc_score.mean())

etc -0.27939016547216705


In [29]:
features = std.transform(features)
features

array([[-2.50223719, -7.15066172, -1.43341916, ...,  4.36162364,
        -1.21578893, -1.19307472],
       [ 1.65008313, -7.19401166, -1.42726845, ..., -1.76673244,
        -1.21578893, -1.19307472],
       [ 1.65008313, -7.19130229, -1.42403124, ..., -1.76673244,
        -1.21578893, -1.19307472],
       ...,
       [-2.50223719, -7.16420857, -1.42985822, ..., -1.76673244,
        30.84608412, -1.19307472],
       [ 1.65008313, -7.21568663, -1.41788054, ..., -1.76673244,
        -1.21578893, -1.19307472],
       [-2.50223719, -7.11543989, -1.43212427, ..., -1.76673244,
        -1.21578893, -1.19307472]])

In [30]:
label

0       1
1       1
2       0
3       1
4       0
       ..
1353    1
1354    0
1355    1
1356    0
1357    0
Name: class, Length: 1358, dtype: int64

In [41]:
from sklearn.model_selection import GridSearchCV
params = { 'n_estimators': [50,60,70,80],
           'criterion': ['gini','entropy'],
           'bootstrap': [True,False],
           'max_features' : [7,8,9,10]
         }
etc2 = ExtraTreesClassifier()
grid_search_etc = GridSearchCV(etc2, param_grid=params, cv=5, scoring='neg_log_loss', verbose=1)
grid_search_etc.fit(features,label)

Fitting 5 folds for each of 64 candidates, totalling 320 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 320 out of 320 | elapsed:   51.4s finished


GridSearchCV(cv=5, error_score=nan,
             estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                                            class_weight=None, criterion='gini',
                                            max_depth=None, max_features='auto',
                                            max_leaf_nodes=None,
                                            max_samples=None,
                                            min_impurity_decrease=0.0,
                                            min_impurity_split=None,
                                            min_samples_leaf=1,
                                            min_samples_split=2,
                                            min_weight_fraction_leaf=0.0,
                                            n_estimators=100, n_jobs=None,
                                            oob_score=False, random_state=None,
                                            verbose=0, warm_start=False),
             iid='deprecate

In [42]:
grid_search_etc.best_params_

{'bootstrap': True, 'criterion': 'gini', 'max_features': 9, 'n_estimators': 60}

In [33]:
grid_search_etc.cv_results_

{'mean_fit_time': array([0.13438034, 0.22076817, 0.31355562, 0.39834166, 1.02545571,
        0.10878315, 0.21277003, 0.32315354, 0.4735322 , 1.09264774,
        0.11198192, 0.22876654, 0.32795224, 0.48953156, 1.17156854,
        0.06878905, 0.13598137, 0.20157247, 0.26556344, 0.65910869,
        0.07998734, 0.1343812 , 0.19837322, 0.31195583, 0.68150258,
        0.07518911, 0.13598104, 0.20817399, 0.27836113, 0.7726922 ,
        0.06719017, 0.15518131, 0.22876711, 0.27996125, 0.7838922 ,
        0.09278755, 0.18717446, 0.21596928, 0.37594972, 1.13156462,
        0.17757602, 0.33594828, 0.35515294, 0.34555297, 0.83028498,
        0.07678881, 0.25276656, 0.27516212, 0.30900517, 0.81748505,
        0.07998857, 0.15837612, 0.27036462, 0.32635665, 1.10385275,
        0.13438115, 0.3279521 , 0.29435916, 0.35410547, 0.98277488,
        0.10558362, 0.26484079, 0.39354362, 0.44331799, 1.13903594,
        0.12638054, 0.2500927 , 0.34235101, 0.45273547, 1.14064155,
        0.14078031, 0.29595618,

In [39]:
grid_search_etc.best_estimator_

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='entropy', max_depth=None, max_features=7,
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=60, n_jobs=None,
                     oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [46]:
etc_gs = grid_search_etc.best_estimator_

scores = cross_val_score(etc_gs, features, label, scoring = 'neg_log_loss', cv = StratifiedKFold(n_splits = 5, shuffle = True))

print(scores.mean())

-0.2765832125186367


In [50]:
preds = etc_gs.predict_proba(X_val)

from sklearn.metrics import log_loss

log_loss(y_val, preds)

0.62134544668895

In [52]:
etc = ExtraTreesClassifier(n_estimators=80, max_features=7)
etc.fit(X_train,y_train)

preds = etc.predict_proba(X_val)

log_loss(y_val, preds)

0.2562783493904025

In [53]:
test = pd.read_csv('D:/IMS Proschool/Business Analytics/Practice/Self/Glass_Quality_Participants_Data/Test.csv')
test.head()

grade_A_Component_1  grade_A_Component_2  max_luminosity  thickness  xmin  \
0                    1                    0             123         65    33   
1                    0                    1             158         99   125   
2                    0                    1             120         35    64   
3                    0                    1             130         39    57   
4                    1                    0             142         75    23   

   xmax      ymin      ymax  pixel_area     log_area  x_component_1  \
0    54   1646439   1646893         632   632.391749              0   
1   132    189874    189529         421   421.928609              0   
2    75  12986873  12986862         272   272.212214              1   
3   177    309634    310824        3312  3312.310581              0   
4    79   5368307   5367467         862   862.499179              0   

   x_component_2  x_component_3  x_component_4  x_component_5  
0              1              0              0              0  
1              0              0              0              0  
2              0              0              0              0  
3              0              1              0              0  
4              0              0              0              0

In [54]:
test = test.drop(['grade_A_Component_2'], axis=1)

In [55]:
test.shape

(583, 14)

In [56]:
X_train.shape

(1086, 14)

In [58]:
features

array([[-2.50223719, -7.15066172, -1.43341916, ...,  4.36162364,
        -1.21578893, -1.19307472],
       [ 1.65008313, -7.19401166, -1.42726845, ..., -1.76673244,
        -1.21578893, -1.19307472],
       [ 1.65008313, -7.19130229, -1.42403124, ..., -1.76673244,
        -1.21578893, -1.19307472],
       ...,
       [-2.50223719, -7.16420857, -1.42985822, ..., -1.76673244,
        30.84608412, -1.19307472],
       [ 1.65008313, -7.21568663, -1.41788054, ..., -1.76673244,
        -1.21578893, -1.19307472],
       [-2.50223719, -7.11543989, -1.43212427, ..., -1.76673244,
        -1.21578893, -1.19307472]])

In [59]:
test = std.transform(test)

In [60]:
etc.fit(features,label)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features=7,
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=80, n_jobs=None,
                     oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [61]:
preds = etc.predict_proba(test)

In [62]:
preds

array([[0.475 , 0.525 ],
       [0.6625, 0.3375],
       [0.5375, 0.4625],
       ...,
       [0.4875, 0.5125],
       [0.5375, 0.4625],
       [0.625 , 0.375 ]])

In [63]:
pred = etc.predict(test)
pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,

In [65]:
sub = pd.read_excel('D:/IMS Proschool/Business Analytics/Practice/Self/Glass_Quality_Participants_Data/Sample_Submission.xlsx')
sub.head()

1         2
0  0.600493  0.399507
1  0.532010  0.467990
2  0.892149  0.107851
3  0.694834  0.305166
4  0.740557  0.259443

In [68]:
sub[1] = preds[:,1]
sub[2] = preds[:,0]

In [69]:
sub.to_excel('D:/IMS Proschool/Business Analytics/Practice/Self/Glass_Quality_Participants_Data/Final_Submission.xlsx', index=False)